version: "3"
services: 
    nginx:
        image: nginx:stable-alpine
        ports: 
            - "3000:80"  # mapping port: 3000 to port: 80
        volumes: 
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    node-app:
        build: .
        image: henrysweb/node-app
        # ports: 
        #     - "3000-3001:3000"  # removed after adding nginx image
        # volumes: 
        #     - ./:/app
        #     - ./app/node_modules
        environment: 
            - PORT=3000
        # env_file: 
        #     - ./.env
        depends_on:         # run mongo first
            - mongo
    mongo:
        image: mongo
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=mytestdb
            - MONGO_INITDB_ROOT_PASSWORD=mypassword
        volumes: 
            - mongo-db:/data/db # name volume
    
    redis:
        image: redis

volumes: 
    mongo-db: